#!/bin/sh

SCRIPTNAME=$0

status_chk()
{

  while :
  do
    sudo ipsec status
    echo "Do something; hit [CTRL+C] to stop!"
    sleep 10
  done
  
}


case "$1" in
    start)
        #sudo ./nordvpn-ipsec.py $@
        sudo ./nordvpn-ipsec.py $@
        sudo ipsec restart
        sleep 1
        sudo ipsec up NordVPN
        sleep 1
        ;;
    stop)
        sudo ipsec down NordVPN
        ;;
    status)
        status_chk
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|status}" >&2
        exit 3
        ;;
esac

exit 0
